name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2 ]
    name: PHP ${{ matrix.php }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug
          tools: phpunit:10.*

      - name: Setup Composer token
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        # Laravel & Core
        # run: composer install --prefer-dist --no-interaction --no-progress --no-scripts
        # explorer
        # run: composer install --no-ansi --no-interaction --no-progress --no-scripts
        # https://github.com/wikimedia/composer-merge-plugin/issues/252
        run: composer install --prefer-dist --no-interaction --no-progress --no-plugins --no-scripts
      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Copy environment file
        #          cp .env.ci .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit
